### PR TITLE
V1.4 fix edit appt

### LINKED ISSUE #168: [PE-D][Tester D] Application does not respond when I try to edit an appointment's start time to its end time.
As you can see from the image above, editing the start time of the appointment to the end time of the appointment does not show an expected error message. The application does not crash but it does not respond to this command at all. The error message that is displayed in the picture is for a previous command that I had input. 

The same issue happens if I try to edit the start time of the appointment to a timing thats after the end time of the appointment

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: delishad21/ped#14

### PR DESCRIPTION
**Pull request by ThatGirlJam**
Fixed the bug to check for:
- when user edits new endtime to be before/= curr start time, error
- when user edits new starttime to be after/= curr endtime, error 
- when user tries new start and endtime that is an invalid timePeriod, error

Added tests for these checks.

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/EditApptCommandParser.java [hunk 1]
```diff
@@ -76,6 +76,22 @@ public EditApptCommand parse(String args) throws ParseException {
...
+        //Check if valid new time period (both new start and end time given)
+        if (argMultimap.getValue(PREFIX_NEW_END_TIME).isPresent()
+                && argMultimap.getValue(PREFIX_NEW_START_TIME).isPresent()) {
+            ParserUtil.parseTimePeriod(argMultimap.getValue(PREFIX_NEW_START_TIME).get(),
+                    argMultimap.getValue(PREFIX_NEW_END_TIME).get());
+        }
+
+        //extra check to parse if new end time before current start time (only new end time given)
+        //will check the vice versa in command itself as curr end time not an input
+        if (argMultimap.getValue(PREFIX_NEW_END_TIME).isPresent()
```
Comment (dayn-1) [inline src/main/java/seedu/address/logic/parser/EditApptCommandParser.java]: Since EditApptCommand throws CommandException when the TimePeriod is invalid, not sure if the additional checks added from line 80 to 93 here are redundant?

**Review by dayn-1 — COMMENTED** [review]
Thanks for fixing this @ThatGirlJam !

File: src/main/java/seedu/address/logic/parser/EditApptCommandParser.java (hunk 1 above)
Comment (ThatGirlJam) [reply src/main/java/seedu/address/logic/parser/EditApptCommandParser.java]: True! Was thinking of it as a way to check before it gets passed to the EditApptCommand, not sure if it would help or reduce performance. Should I perhaps remove the extra check then?

Comment (dayn-1) [reply src/main/java/seedu/address/logic/parser/EditApptCommandParser.java]: I see, that works too! But I guess the extra check wouldn't account for the case where only the new start time is provided and it exceeds the appointment's current end time (not available to parser). In that case, not sure if the extra checks are comprehensive enough to be useful and should be removed instead. What do you think?

Comment (ThatGirlJam) [reply src/main/java/seedu/address/logic/parser/EditApptCommandParser.java]: Sounds good, will remove it 👍

**Review by dayn-1 — APPROVED** [review]
