### PR TITLE
Fix bug that extra long inputs were cut off in UI

### LINKED ISSUE #102: Unable to read Type and Note given extremely long input
Screenshot 2024-04-03 at 4 44 16 PM

As we have no way to get the entire string for appointment type and notes, shall we limit the number of characters so that it shows up properly in the UI?

### PR DESCRIPTION
**Pull request by limrik**
Update UI to fix issue that extra long inputs were getting cut-off.

### CODE REVIEW

File: src/main/java/seedu/address/model/patient/Email.java [hunk 1]
```diff
@@ -18,9 +18,10 @@ public class Email {
             + "2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels "
             + "separated by periods.\n"
             + "The domain name must:\n"
-            + "    - end with a domain label at least 2 characters long\n"
+            + "    - end with a domain label at least 2 characters\n"
             + "    - have each domain label start and end with alphanumeric characters\n"
-            + "    - have each domain label consist of alphanumeric characters, separated only by hyphens, if any.";
+            + "    - have each domain label consist of alphanumeric characters, separated only by hyphens, if any.\n"
+            + "3. The total email length has a maximum limit of 320 characters.";
```
Comment (dayn-1) [inline src/main/java/seedu/address/model/patient/Email.java]: Maybe this can reference the `EMAIL_CHARACTER_LIMIT` above

File: src/main/java/seedu/address/model/patient/Email.java [hunk 2]
```diff
@@ -18,9 +18,10 @@ public class Email {
             + "2. This is followed by a '@' and then a domain name. The domain name is made up of domain labels "
             + "separated by periods.\n"
             + "The domain name must:\n"
-            + "    - end with a domain label at least 2 characters long\n"
+            + "    - end with a domain label at least 2 characters\n"
```
Comment (dayn-1) [inline src/main/java/seedu/address/model/patient/Email.java]: Maybe can keep "long"

File: src/main/java/seedu/address/ui/PatientCard.java [hunk 3]
```diff
@@ -56,8 +56,8 @@ public PatientCard(Patient patient, int displayedIndex) {
         nric.setText(patient.getNric().value);
         dob.setText(patient.getDob().toString());
         phone.setText(patient.getPhone().value);
-        address.setText(patient.getAddress().value);
-        email.setText(patient.getEmail().value);
+        address.setText("Address: " + patient.getAddress().value);
+        email.setText("Email: " + patient.getEmail().value);
```
Comment (dayn-1) [inline src/main/java/seedu/address/ui/PatientCard.java:60]: Not sure if we want to have "Parameter: " for all or just these 2

**Review by dayn-1 — APPROVED** [review]
LGTM! Thanks @limrik
